### PR TITLE
py312 for pynng 0.7.1

### PR DESCRIPTION
**Pull request by carlodri**
This PR is to build py312 for `pynng` 0.7.1

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@jan-janssen do you know how I can  add the migration for Python 3.12? Do i need to manually copy here the file in the `.ci_support/migrations` folder?

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
We already did this in https://github.com/conda-forge/pynng-feedstock/pull/16

**Comment by jan-janssen** [comment]
Oh, I see you want to do it for 0.7.1 - yes, you can just copy the migration file from the main branch.

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
> Oh, I see you want to do it for 0.7.1 - yes, you can just copy the migration file from the main branch.

thank you!

**Comment by carlodri** [comment]
FYI @jan-janssen I have opened [this issue](https://github.com/codypiersall/pynng/issues/117) on the upstream repo. I would be interested in having updated versions of `pynng`, but I'm not sure if the code owner is interested. In case, would you be interested in helping me with a new python package (not a feedstock, I mean a new Python package) that brings updated support for NNG on Python? But let's see also what the code owner has to say.

**Pull request merged**
