### PR TITLE
Fix osx-arm64 ImportError in v0.8.0

### LINKED ISSUE #24: ImportError when using pynng `v0.8.0` on osx-arm64
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When trying to import the conda-forge version of `pynng` on `osx-arm64`, an error occurs:

```
>>> import pynng
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/Users/thomasmarwitz/mambaforge/envs/pipdag/lib/python3.12/site-packages/pynng/__init__.py", line 3, in <module>
  from ._nng import lib, ffi
ImportError: dlopen(/Users/thomasmarwitz/mambaforge/envs/pipdag/lib/python3.12/site-packages/pynng/_nng.abi3.so, 0x0002): symbol not found in flat namespace '_nng_aio_abort'
```

### Installed packages

```shell
Name                      Version                   Build    Channel
bzip2                     1.0.8                h93a5062_5    conda-forge
ca-certificates           2023.11.17           hf0a4a13_0    conda-forge
cffi                      1.16.0          py311h4a08483_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.44.2               h091b4b1_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
mbedtls                   3.3.0                hb7217d7_0    conda-forge
ncurses                   6.4                  h463b476_2    conda-forge
nng                       1.6.0                hebf3989_3    conda-forge
openssl                   3.2.0                h0d3ecfb_1    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pynng                     0.8.0           py311h92babd0_0    conda-forge
python                    3.11.7          hdf0ec26_1_cpython    conda-forge
python_abi                3.11                    4_cp311    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
```

### Environment info

```shell
active environment : pynng
    active env location : /Users/thomasmarwitz/mambaforge/envs/pynng
            shell level : 2
       user config file : /Users/thomasmarwitz/.condarc
 populated config files : /Users/thomasmarwitz/mambaforge/.condarc
                          /Users/thomasmarwitz/.condarc
          conda version : 23.10.0
    conda-build version : 3.27.0
         python version : 3.9.18.final.0
       virtual packages : __archspec=1=m2
                          __osx=14.1.1=0
                          __unix=0=0
       base environment : /Users/thomasmarwitz/mambaforge  (writable)
      conda av data dir : /Users/thomasmarwitz/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/thomasmarwitz/mambaforge/pkgs
                          /Users/thomasmarwitz/.conda/pkgs
       envs directories : /Users/thomasmarwitz/mambaforge/envs
                          /Users/thomasmarwitz/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.10.0 requests/2.31.0 CPython/3.9.18 Darwin/23.1.0 OSX/14.1.1 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by ThomasMarwitzQC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

See https://github.com/conda-forge/pynng-feedstock/issues/24#issuecomment-1905739939 for an explanation how this PR attempts to fix #24

### CODE REVIEW

**Comment by ThomasMarwitzQC** [comment]
@conda-forge-admin, please rerender

**Comment by ThomasMarwitzQC** [comment]
@carlodri I think this should fix the problem. I previously made a mistake when pointing to the dependencies `nng` and `mbedtls`.

I also added myself as a code owner, are you ok with that?

**Comment by carlodri** [comment]
> I also added myself as a code owner, are you ok with that?

absolutely, thank you!

**Comment by carlodri** [comment]
so, if I understand correctly, now you are no more pulling `mbedtls` and `nng` from conda-forge but resorted back to building them inside `pynng`, is that correct?

**Comment by carlodri** [comment]
sorry, forget my last comment, I didn't look carefully at the changes you made!

**Comment by ThomasMarwitzQC** [comment]
Ok, no problem.

I just made a mistake by putting the `host` dependencies also in the `build` dependencies section (I used a wrong prefix and would get an error otherwise. With the new prefix, it works 😃 ). This PR just remedies this.

I also tried to explain it more carefully in https://github.com/conda-forge/pynng-feedstock/issues/24#issuecomment-1905739939 :D

**Review by pavelzw — APPROVED** [review]
No more linker warnings, LGTM

**Comment by ThomasMarwitzQC** [comment]
@conda-forge-admin, please rerender

**Comment by ThomasMarwitzQC** [comment]
> > I also added myself as a code owner, are you ok with that?
> 
> absolutely, thank you!

Also added myself as recipe maintainer as the codeowners file is auto generated

**Comment by ThomasMarwitzQC** [comment]
@carlodri Sadly, the tests (`import pynng`) cannot be emulated for osx-arm64. Therefore, I'll install and try to import as soon as this is merged :)

**Comment by ThomasMarwitzQC** [comment]
@carlodri it worked :)

**Pull request merged**
