### PR TITLE
pynng v0.8.0, all plattforms

### PR DESCRIPTION
**Pull request by ThomasMarwitzQC**
> [!NOTE]
> This started as a try to make the version back then `0.7.3` work with `osx`. However, in the newest version of pynng `0.8.0`, the author ensured compatibility of `pynng` with `nng=1.6.0` and `mbedtls=3.5.1`. 
>
> As `nng=1.6.0` and `mbedtls=3.3.0` are available on conda-forge for not-win plattforms, this approach uses these conda-forge versions for linux and osx, this seems to fix the issues that arose in #22 and #23 due to the vendored dependencies.

The patch `fix-osx-linux.patch` removes the vendored dependencies `nng` and `mbedtls` for not-win systems. 
Therefore, it partly addresses #12.

The reason the dependencies are un-vendored only for linux and osx is that at the moment, mbedtls is not available for windows (but should be soon-ish https://github.com/conda-forge/mbedtls-feedstock/pull/15). Another thing to consider is the author mentioning that he ran into runtime errors when trying to install `nng` and `mbedtls` as external dependencies on windows: https://github.com/codypiersall/pynng/issues/117#issuecomment-1854018454.

If `mbedtls` becomes available on windows, we might give it another try to un-vendor the dependencies also for windows. If that works, we might even be able to include these changes upstream.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ThomasMarwitzQC** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@conda-forge-admin please rerender

**Comment by pavelzw** [comment]
With nng now being available for all platforms on conda-forge (https://github.com/conda-forge/nng-feedstock/pull/8), it could make sense to just use the version built directly on conda-forge and patch out the nng build steps for pynng in `setup.py`.

**Comment by carlodri** [comment]
@conda-forge-admin please rerender

**Comment by carlodri** [comment]
> With nng now being available for all platforms on conda-forge ([conda-forge/nng-feedstock#8](https://github.com/conda-forge/nng-feedstock/pull/8)), it could make sense to just use the version built directly on conda-forge and patch out the nng build steps for pynng in `setup.py`.

the problem is that currently `pynng` is compatible only with an older version of `nng`, not sure which one. So we should back-release `nng` on conda-forge to get this working.

**Comment by ThomasMarwitzQC** [comment]
@conda-forge-admin please rerender

**Comment by ThomasMarwitzQC** [comment]
@conda-forge-admin please rerender

**Comment by ThomasMarwitzQC** [comment]
@carlodri and @jan-janssen, what do you think?

**Comment by carlodri** [comment]
Thanks for your work @ThomasMarwitzQC! Looks fine to me, I'm going to merge.

My only concern at the moment is that the tests here are quite "thin", just the Python import, but we might improve that later.

**Comment by ThomasMarwitzQC** [comment]
@carlodri when testing locally, I also ran the example in the README: 

```
from pynng import Pair0

with Pair0(listen='tcp://127.0.0.1:54321') as s1, \
        Pair0(dial='tcp://127.0.0.1:54321') as s2:
    s1.send(b'Well hello there')
    print(s2.recv())
```

Did you have such a test in mind or something else?

**Comment by carlodri** [comment]
Yes, something like that, simple send/receive on a Pub/Sub, Req/Rep etc., which might catch something more than a simple import.

**Comment by ThomasMarwitzQC** [comment]
Ok, there are some other example interactions, we might take some of them as a test.

And @carlodri could you re-run the timed-out Python 3.12 osx build?

**Comment by carlodri** [comment]
Uhm...I don't think I can do that....or at least I cannot find a way...

**Comment by ThomasMarwitzQC** [comment]
Sadly, I discovered a problem when importing on `osx-arm64`:

```
>>> import pynng
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/Users/thomasmarwitz/mambaforge/envs/pipdag/lib/python3.12/site-packages/pynng/__init__.py", line 3, in <module>
  from ._nng import lib, ffi
ImportError: dlopen(/Users/thomasmarwitz/mambaforge/envs/pipdag/lib/python3.12/site-packages/pynng/_nng.abi3.so, 0x0002): symbol not found in flat namespace '_nng_aio_abort'
```

I didn't run into this problem when building locally. I don't now whether this is due to the cross compile taking place. But the `import pynng` seemed to work on conda-forge 🤔

**Comment by carlodri** [comment]
I'm afraid this has something to do with the  packaging of `nng` in conda-forge, but I don't have time to investigate right now...

Maybe it's best if you open an issue against this so we can gather evidence there.

**Comment by ThomasMarwitzQC** [comment]
No need to investigate the packaging of `nng`, if #25 works, I was due to a mistake I made in the `meta.yml`.

**Pull request merged**
