### PR TITLE
Use external libraries for Mac OS X and Linux 

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
I tried to build the windows library for `mbedtls` but that did not work https://github.com/conda-forge/mbedtls-feedstock/pull/9 - so for now I just try to link Linux and Mac OS X to the external libraries.

**Comment by carlodri** [comment]
@jan-janssen have you seen this: https://github.com/codypiersall/pynng/pull/92? It might help.

**Comment by jan-janssen** [comment]
```
import: 'pynng'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pynng_1659654544274/test_tmp/run_test.py", line 2, in <module>
    import pynng
  File "/home/conda/feedstock_root/build_artifacts/pynng_1659654544274/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/pynng/__init__.py", line 3, in <module>
    from ._nng import lib, ffi
ImportError: /home/conda/feedstock_root/build_artifacts/pynng_1659654544274/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/pynng/_nng.abi3.so: undefined symbol: nng_tls_config_hold
```

**Pull request closed without merging**
